[build]
  command = "npm run build:client"
  functions = "netlify/functions"
  publish = "dist/spa"


[functions]
  node_bundler = "esbuild"
  # Ensure these Node modules are packaged with the serverless functions
  external_node_modules = ["express", "cors", "cookie-parser"]
  
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"

# SPA fallback: send all non-file routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
